### ISSUE TITLE
Ability to Send RVN and RVN Assets

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#58]
**Describe the User Story:**
As an User
I want to Sending RVN and RVN Assets

**Describe What You'd Like:**
Much of the functionality for Sending RVN also applies to RVN Assets. such as being able to specify: address, scan address, fee level, send amount, send all, see the usd amount

**Story:**
- [ ] https://github.com/moontreeapp/raven_front/issues/23
- [ ] https://github.com/moontreeapp/raven_back/issues/31

**Tasks:**
- [ ] https://github.com/moontreeapp/raven_front/issues/24
- [ ] https://github.com/moontreeapp/raven_front/issues/21
- [ ] https://github.com/moontreeapp/raven_front/issues/4
- [x] https://github.com/moontreeapp/raven_front/issues/75
- [x] https://github.com/moontreeapp/raven_front/issues/76
- [x] https://github.com/moontreeapp/raven_front/issues/77
