### ISSUE TITLE
Assets UI

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#59]
**Describe the User Story:**
As a User
I want a user interface that is clean and crisp
So that I enjoy using the app

**Describe What You'd Like:**
Much of that comes down to the general design (UX) but some of it comes down to specific things in the interface that can be made clean. like spinners for example

**Tasks**
- [ ] https://github.com/moontreeapp/raven_front/issues/38
- [x] https://github.com/moontreeapp/raven_front/issues/27
- [ ] https://github.com/moontreeapp/raven_front/issues/10
- [ ] https://github.com/moontreeapp/raven_front/issues/11

**Comment by lastmeta** [comment]
This Story is confusing, we're closing
