### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#60]
**Describe the User Story:**
As a User
I want to see everything I hold on the homescreen
So that I know what I have

**Describe What You'd Like:**
I should be able to: see name, see logo, see balance, see transactions, see differentiation of unique vs master asset,

**Stories**
- [x] https://github.com/moontreeapp/raven_front/issues/72

**Tasks:**
- [x] https://github.com/moontreeapp/raven_front/issues/67
- [x] https://github.com/moontreeapp/raven_front/issues/66
- [x] https://github.com/moontreeapp/raven_front/issues/85
- [x] https://github.com/moontreeapp/raven_front/issues/65
- [x] https://github.com/moontreeapp/raven_front/issues/68
