### ISSUE TITLE
User Security

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#61]
**Describe the User Story:**
As a User
I want to control the level of security I'm happy with

**Stories**
- [ ] https://github.com/moontreeapp/raven_back/issues/41

**Tasks:**
- [x] https://github.com/moontreeapp/raven_back/issues/16
- [x] https://github.com/moontreeapp/raven_back/issues/37
- [x] https://github.com/moontreeapp/raven_front/issues/13
- [ ] https://github.com/moontreeapp/raven_back/issues/39
- [ ] https://github.com/moontreeapp/raven_back/issues/28

**Comment by lastmeta** [comment]
Next itt
- [ ] https://github.com/moontreeapp/raven_back/issues/38
