### ISSUE TITLE
Accounts Drawer

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#72]
**Describe The Bug**
As a user I want to see a be able to change my accounts, and see my settings in the drawer

**Ideal**
make it look like metamask should show settings, and have a pull up drawer to list accounts instead
"(settings page in pull out, change acocunts with pull up)"

**Tasks**
- [x] https://github.com/moontreeapp/raven_front/issues/82
- [x] https://github.com/moontreeapp/raven_front/issues/83
- [x] https://github.com/moontreeapp/raven_front/issues/84
