### ISSUE TITLE
Debug crash report system

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#87]
**Prerequisites**
 - [ ] Did you perform a cursory search?
 - [x] Are you running the latest version?

As a user, when I have a problem, I want to be able to send something to a dev so they can fix it for me.

**Describe the solution you'd like**
rather than rolling our own we should use a system that's out there: datadog or other

**Additional context**
Datadog has been implemented, but we ran into a glitch with cocoapods and it on ios so we may implement a different one instead if we can't solve that issue, idk...

**Created from**
https://github.com/moontreeapp/raven_front/issues/6

**Tasks**
- [ ] moontreeapp/raven_back#50
